//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NET_MVC_NESTED_YAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notes
    {
        public int NoteID { get; set; }
        public string Notes1 { get; set; }
    }
}
